pipeline:
  name: Warp CLI Setup
  trigger_mode: ON_EVERY_PUSH
  ref_name: master

actions:
  - action: "Run Docker Container 1"
    type: "DOCKER"
    image_name: "yourusername/warp-container"
    commands:
      - echo "Container 1"
      - warp-cli register
      - warp-cli connect
      - warp-cli --accept-tos status
      - ip -4 addr show dev eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'

  - action: "Run Docker Container 2"
    type: "DOCKER"
    image_name: "yourusername/warp-container"
    commands:
      - echo "Container 2"
      - warp-cli register
      - warp-cli connect
      - warp-cli --accept-tos status
      - ip -4 addr show dev eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'

  - action: "Run Docker Container 3"
    type: "DOCKER"
    image_name: "yourusername/warp-container"
    commands:
      - echo "Container 3"
      - warp-cli register
      - warp-cli connect
      - warp-cli --accept-tos status
      - ip -4 addr show dev eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'

  - action: "Run Docker Container 4"
    type: "DOCKER"
    image_name: "yourusername/warp-container"
    commands:
      - echo "Container 4"
      - warp-cli register
      - warp-cli connect
      - warp-cli --accept-tos status
      - ip -4 addr show dev eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'

  - action: "Run Docker Container 5"
    type: "DOCKER"
    image_name: "yourusername/warp-container"
    commands:
      - echo "Container 5"
      - warp-cli register
      - warp-cli connect
      - warp-cli --accept-tos status
      - ip -4 addr show dev eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
